namespace DetailTEC.REST_API_UserModel
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json.Converters;
    /// <summary>
    /// Class that packs User objects into an array called UserModel
    /// author Jose Antonio Espinoza.
    /// </summary>
    public partial class UserModel
    {
        [JsonProperty("users")]
        public User[] Users { get; set; }
    }
    /// <summary>
    /// Class that creates User objects from data given by the app for managing, creatings and showing methods.
    /// author Jose Antonio Espinoza.
    /// </summary>
    public partial class User
    {
        [JsonProperty("nombreCompleto")]
        public string Name { get; set; }

        [JsonProperty("telefonos")]
        public List<String> Telefonos { get; set; }

        [JsonProperty("cedula")]
        public string ID { get; set; }

        [JsonProperty("correo")]
        public string Email { get; set; }

        [JsonProperty("direccion")]
        public string Address { get; set; }

        [JsonProperty("usuario")]
        public string Username { get; set; }

        [JsonProperty("contrasena")]
        public string Password { get; set; }

        [JsonProperty("puntos")]
        public int Points { get; set; }
    }

    public partial class User
    {
        /// <summary>
        /// Methods that converts a json file to an object type
        /// author Jose Antonio Espinoza.
        /// </summary>
        public static User FromJson(string json) => JsonConvert.DeserializeObject<User>(json, DetailTEC.REST_API_UserModel.Converter.Settings);
    }

    public static class Serialize
    {
        /// <summary>
        /// Methods that converts an object type into a json file
        /// author Jose Antonio Espinoza.
        /// </summary>
        public static string ToJson(this User self) => JsonConvert.SerializeObject(self, DetailTEC.REST_API_UserModel.Converter.Settings);
    }
    /// <summary>
    /// Methods autogenerated by Newtonsoft.json
    /// author Jose Antonio Espinoza.
    /// </summary>
    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }
        /// <summary>
        /// Creates a unique singleton instance of the string parser.
        /// author Jose Antonio Espinoza.
        /// </summary>
        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}